public void testDontRemoveBreakInTryFinallySwitch() throws Exception {
    testSame("function f() {b:try{throw 9} finally {switch(x) {case 1: break b} } return 1;}");
}